services:
  mysql:
    image: mysql:8.0.34
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: pass
    volumes:
      - mysql_data:/var/lib/mysql

  postgres:
    image: postgres:14-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  node-app:
    build: ./gate-simulator
    image: node-app:1.0
    container_name: js-container
    ports:
      - '9999:9999'
    restart: unless-stopped

volumes:
  mysql_data:
  postgres_data:


